### ISSUE TITLE
question : How is the input folder supposed to be?

### ISSUE THREAD

**Issue by sid-ks** [Narayana-Rao/PolSAR-tools#5]
Hi,

I have processed Sentinel-1 SLC data and while exporting in SNAP it simply makes a new folder "/home/user/output/" inside of which there are .bin and .hdr files of C11/12/ and 22 _real and _imag files.

The Qgis plugin doesnt seem to recognize this folder as correct. 

The error log says -

```
->> Calculating DpRVI... 
->> Error!! Invalid data folder.
```

Can you please inform why this is being raised?

Thank you.

**Comment by Narayana-Rao** [comment]
I have just updated the repository with sample/test data. Please refer that folder for file format.

**Comment by sid-ks** [comment]
Hi Narayan, thanks for the lead.

It is still not able to read the folder. My folder has the all files that are present in your sample data.

I also tried your sample data folder.

This is the path to the folder "/home/username/SAR/sample_data/" , inside of which all the .bin and .hdr files are present.

Just for more context - Im on a Linux OS.

--------------------------------

## EDIT

I am using Sentinel-1 hence I choose Dual-pol, and try the DpRVI parameter with 5x5 window.

When I click "Process" it won't run, and returns the same error as before.

```
->> Calculating DpRVI... 
->> Error!! Invalid data folder.
```

**Comment by Narayana-Rao** [comment]
Hi, the path should point the matrix folder, something like this ../C3 or ../C2 or ../T3 
In your case it should be like  ```/home/username/SAR/sample_data/dual_pol/C2_VVVH```. 

Please let me know if it works.

**Comment by sid-ks** [comment]
Sorry it still does not work. 

Here's a screenshot of my folder contents and QGIS plugin GUI.

![MRS_errors](https://user-images.githubusercontent.com/73898277/103775145-a96e0700-5053-11eb-8242-781f6bb3e29a.png)

Also tried folder name as C2_VVVH

My doubt is, why is the folder name in plugin not having the last forward slash ? "/"
Can that be the issue? I mean should the path not be 
```/home/username/SAR/sample_data/dual_pol/C2_VVVH/``` , 
instead of 
```/home/username/SAR/sample_data/dual_pol/C2_VVVH``` ?

Also, when I click on **View Data**, it opens the folder correctly.

Thanks for the support.

**Comment by Narayana-Rao** [comment]
We have traced and fixed the issue. Please try downloading the zip from GitHub and install. Hopefully it should work.  Instructions to install using zip file are in readme.
 
Thank you for raising the issue.

**Comment by sid-ks** [comment]
Hi, Thanks for fixing it. Now the plugin works for DpRVI. Thank you!

**Comment by Narayana-Rao** [comment]
Ok, Thank you!
